[project]
name = "wechat"
version = "0.1.0"
description = "wechat"
readme = "README.md"
requires-python = ">=3.8, <4.0"

[tool.nonebot]
adapters = [
    { name = "OneBot V12", module_name = "nonebot.adapters.onebot.v12" }
]
plugins = []
plugin_dirs = ["plugins"]
builtin_plugins = ["echo"]
